FROM pimcore/pimcore:php8.1-latest

RUN apt-get -y update && \
    # Install required package
    apt-get install -y --no-install-recommends graphviz && \
    # clean up
    apt-get remove -y automake libtool nasm pkg-config libz-dev build-essential g++ && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* ~/.composer